#!/bin/bash

echo "🔐 Credenciales de acceso del sistema"
echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│                    PREVIEW - BRANCH DEVELOP             │"
echo "│                                                         │"
echo "│  SuperAdmin: admin@remitero.com / daedae123            │"
echo "│  Admin:      admin@empresademo.com / admin123           │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "🌐 URLs de acceso:"
echo "• Preview: https://remitero-dev.vercel.app/"
echo "• Production: https://v0-remitero.vercel.app/"
echo ""
echo "📋 Roles disponibles:"
echo "• SUPERADMIN: Acceso completo al sistema"
echo "• ADMIN: Administración de empresa"
echo "• USER: Usuario estándar"
echo ""
echo "💡 Copia y pega estas credenciales cuando necesites acceder al sistema"
